todo/accounts/urls.py
from django.urls import path
from .views import (
    user_login_view, user_register_view,
    IndexPageView, UserLogoutView, 
    AddTodoView,TodoListView,
    UpdateTodo, TodoDeleteView)
app_name = 'accounts'


urlpatterns = [
    path('login/', user_login_view, name="login"),
    path('logout/', UserLogoutView.as_view(), name="logout"),
    path('register/', user_register_view, name="register"),
    path('index/', IndexPageView.as_view(), name="index"),
    path('add/', AddTodoView.as_view(), name="add"),
    path('view/', TodoListView.as_view(), name="view"),
    path('update/<int:pk>/', UpdateTodo.as_view(), name="update"),
    path('delete/<int:pk>/', TodoDeleteView.as_view(), name="delete"),
]

todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
]

todo/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class UserProfileModel(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    bio = models.CharField(max_length=150)
    dob = models.DateField(null=True)
    
    @receiver(post_save,sender=User)
    def create_user_profile(sender,instance,created,**kwargs):
        if created:
            UserProfileModel.objects.create(user=instance)

    @receiver(post_save,sender=User)
    def update_user_profile(sender,instance,created,**kwargs):
        instance.userprofilemodel.save()

class Todo(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    todo = models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user


todo/accounts/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import UserProfileModel, Todo

class UserDetailsForm(ModelForm):
    class Meta:
        model = User
        fields = ['username','password','first_name','last_name']
        widgets = {
            'password' : forms.PasswordInput(attrs={
                'placeholder': 'Password from numbers and letters of the Latin alphabet'
            }),
            'username' : forms.TextInput(attrs={
                'placeholder' : 'Your Username'
            }),
            'first_name' : forms.TextInput(attrs={
                'placeholder' : 'First Name'
            }),
            'last_name' : forms.TextInput(attrs={
                'placeholder' : 'Last Name'
            })
        }

class UserProfileDetailsForm(ModelForm):
    class Meta:
        model = UserProfileModel
        fields = ['bio','dob']
        widgets = {
            'bio' : forms.TextInput(attrs={
                'placeholder': 'Say us about You!!'
            }),
        }

class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150,widget=forms.PasswordInput())


class AddTodo(ModelForm):
    class Meta:
        model = Todo
        fields = ['todo']
        widgets = {
            'todo' : forms.TextInput(attrs={
                'placeholder' : 'Todo of Your'
            })
        }

todo/accounts/views.py
from django.shortcuts import render, redirect

from .models import UserProfileModel, Todo
from .forms import UserDetailsForm, UserProfileDetailsForm,UserLoginForm, AddTodo

from django.contrib.auth import get_user_model, authenticate,login,logout
from django.views.generic import TemplateView, CreateView, UpdateView, DeleteView, ListView, DetailView
from django.contrib.auth.views import LogoutView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

User = get_user_model()

# Create your views here.
@login_required
def user_register_view(request):
    if request.method == 'POST':
        form1 = UserDetailsForm(request.POST)
        form2 = UserProfileDetailsForm(request.POST)
        if form1.is_valid() and form2.is_valid():
            print(form1.data)
            print(form2.data)
            user = User(
                first_name = form1.cleaned_data['first_name'],
                last_name = form1.cleaned_data['last_name'],
                username = form1.cleaned_data['username'],
                password = form1.cleaned_data['password']
            )
            user.save()
            user.set_password(form1.cleaned_data['password'])
            user.userprofilemodel.bio = form2.cleaned_data['bio']
            user.userprofilemodel.dob = form2.cleaned_data['dob']
            user.save()
            return redirect('/accounts/login/')
    elif request.method == 'GET':
        form1 = UserDetailsForm()
        form2 = UserProfileDetailsForm()
    return render(request,'accounts/register.html', { 
        'form1' : form1,
        'form2' : form2 })

def user_login_view(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                username = form.cleaned_data['username'],
                password = form.cleaned_data['password']
            )
            if user:
                login(request,user)
                return redirect('/accounts/index/')
    elif request.method == 'GET':
        form = UserLoginForm()
    return render(request,'accounts/login.html',{'form' : form })


@method_decorator(login_required,name='dispatch')
class IndexPageView(TemplateView):
    template_name = 'accounts/index.html'

@method_decorator(login_required,name='dispatch')
class UserLogoutView(LogoutView):
    next_page = '/accounts/login/'

@method_decorator(login_required,name='dispatch')
class AddTodoView(CreateView):
    model = Todo
    form_class = AddTodo
    template_name = 'accounts/addTodo.html'
    success_url = '/accounts/view/'

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

@method_decorator(login_required,name='dispatch')
class TodoListView(ListView):
    model = Todo
    template_name = 'accounts/viewTodo.html'
    context_object_name = 'todo'

    def get_queryset(self):
        return Todo.objects.filter(user=self.request.user.id)

@method_decorator(login_required,name='dispatch')
class UpdateTodo(UpdateView):
    model = Todo
    form_class = AddTodo
    template_name = 'accounts/editTodo.html'
    success_url = '/accounts/view/'

@method_decorator(login_required,name='dispatch')
class TodoDeleteView(DeleteView):
    model = Todo
    success_url = '/accounts/view/'
    template_name = 'accounts/viewTodo.html'
    


    


todo/accounts/templates/accounts/addTodo.html
{% extends 'accounts/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success" type="submit">Add</button>
  </form>
{% endblock %}

todo/accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Base</title>
</head>
{% if request.user.id %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#"> ToDo's </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:index' %}"> Home </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:view' %}"> View Blogs </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout' %}"> Logout </a>
        </li>
      </ul>
    </div>
  </nav>
{% endif %}




<body>
   <div class="container mt-3">
    {% block content %}
    {% endblock %}
   </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>

</html>

todo/accounts/templates/accounts/editTodo.html
{% extends 'accounts/base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-success" type="submit">Edit</button>
  </form>
{% endblock %}

todo/accounts/templates/accounts/index.html
{% extends 'accounts/base.html' %}

{% block content %}
<h1>This is index </h1>
{% endblock %}

todo/accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Log in</button>
  </form>
{% endblock %}

todo/accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form1.as_p }}
    {{ form2.as_p }}
    <button type="submit">Sign in</button>
  </form>
{% endblock %}

todo/accounts/templates/accounts/viewTodo.html
{% extends 'accounts/base.html' %}

{% load cache %}
{% cache 500 content %}
{% block content %}
  {% for data in todo %}
  todo: {{data.todo}}

  <a href="{% url 'accounts:update' data.id %}">Update Todo </a>\
  <form action="{% url 'accounts:delete' data.id %}" method="POST">
    {% csrf_token %}
    <button type="submit" onclick="return confirm('Do You want to delete ?')">Delete</button>
  </form>
  {%endfor %}
{% endblock %}
{% endcache %}
